dbt_time:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'DBT_SERVICE_ACCT') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ETL_ADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'WH_TRANSFORM') }}"
      database: "DEV"
      schema: "STAGING"
      threads: 2
      connect_timeout: 60
      query_tag: "dbt_time_dev"

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'DBT_SERVICE_ACCT') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ETL_ADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'WH_TRANSFORM') }}"
      database: "DEV"
      schema: "PUBLIC"
      threads: 2
      connect_timeout: 60
      query_tag: "dbt_time_prod"
